[package]
name = "pgn-reader"
version = "0.4.0" # remember to update html_root_url
description = "Fast non-allocating reader for chess games in PGN notation"
repository = "https://github.com/niklasf/rust-pgn-reader.git"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "parser-implementations"]
keywords = ["chess", "pgn"]

[[bench]]
name = "benches"
harness = false

[dependencies]
memchr = "2.0"
btoi = "0.1"
shakmaty = "0.6"

[dev-dependencies]
memmap = "0.6"
madvise = "0.1"
unicase = "2.0"
bencher = "0.1"

[badges]
travis-ci = { repository = "niklasf/rust-pgn-reader", branch = "master" }
