[package]
name = "pgn-reader"
version = "0.27.0" # remember to update html_root_url and benchmarks
description = "Fast non-allocating and streaming reader for chess games in PGN notation"
repository = "https://github.com/niklasf/rust-pgn-reader.git"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "parser-implementations"]
keywords = ["chess", "pgn"]
edition = "2021"

[dependencies]
memchr = "2.2"
btoi = "0.5"
shakmaty = "0.28"
circular = "0.3"

[dev-dependencies]
crossbeam = "0.8"
bzip2 = "0.5"
xz2 = "0.1"
flate2 = "1.0"
lz4 = "1.23"
zstd = "0.13"
